const mongoose = require('mongoose');
const Product = require('./models/Product');

// Connect to database
const mongoURI = 'mongodb+srv://Hackerbase:Amru2003@e-commerce.gqnqlb8.mongodb.net/?retryWrites=true&w=majority&appName=E-commerce';

// 100 Dairy Products with empty image for fallback backgrounds
const products = [
  // Milk Products (1-20)
  {
    name: "Fresh Cow Milk",
    slug: "fresh-cow-milk",
    category: "milk",
    brand: "MilkMitra Farm Fresh",
    price: 60,
    stock: 150,
    unit: "L",
    ratings: 4.8,
    numReviews: 234,
    description: "Pure, fresh cow milk directly from our farms. Rich in calcium and protein for your daily nutrition needs.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Organic Buffalo Milk",
    slug: "organic-buffalo-milk",
    category: "milk",
    brand: "MilkMitra Organic",
    price: 75,
    stock: 100,
    unit: "L",
    ratings: 4.7,
    numReviews: 189,
    description: "100% organic buffalo milk, creamier and richer than cow milk. Perfect for making sweets and desserts.",
    image: "",
    isActive: true
  },
  {
    name: "Full Cream Milk",
    slug: "full-cream-milk",
    category: "milk",
    brand: "MilkMitra Premium",
    price: 70,
    stock: 120,
    unit: "L",
    ratings: 4.6,
    numReviews: 156,
    description: "Full cream milk with 6% fat content. Ideal for coffee, tea, and making creamy dishes.",
    image: "",
    isActive: true
  },
  {
    name: "Toned Milk",
    slug: "toned-milk",
    category: "milk",
    brand: "MilkMitra Lite",
    price: 55,
    stock: 200,
    unit: "L",
    ratings: 4.5,
    numReviews: 201,
    description: "Low fat toned milk with 3% fat. Perfect for health-conscious individuals who want nutritious milk.",
    image: "",
    isActive: true
  },
  {
    name: "Double Toned Milk",
    slug: "double-toned-milk",
    category: "milk",
    brand: "MilkMitra Diet",
    price: 50,
    stock: 180,
    unit: "L",
    ratings: 4.4,
    numReviews: 145,
    description: "Ultra-low fat double toned milk with only 1.5% fat. Best for weight watchers.",
    image: "",
    isActive: true
  },
  {
    name: "Skimmed Milk",
    slug: "skimmed-milk",
    category: "milk",
    brand: "MilkMitra Zero Fat",
    price: 45,
    stock: 150,
    unit: "L",
    ratings: 4.3,
    numReviews: 98,
    description: "Fat-free skimmed milk with all the nutrients. Perfect for fitness enthusiasts.",
    image: "",
    isActive: true
  },
  {
    name: "A2 Milk",
    slug: "a2-milk",
    category: "milk",
    brand: "MilkMitra A2 Pure",
    price: 85,
    stock: 80,
    unit: "L",
    ratings: 4.9,
    numReviews: 312,
    description: "Premium A2 milk from indigenous Gir cows. Easier to digest and rich in A2 beta-casein protein.",
    image: "",
    isActive: true
  },
  {
    name: "Lactose-Free Milk",
    slug: "lactose-free-milk",
    category: "milk",
    brand: "MilkMitra Easy Digest",
    price: 80,
    stock: 90,
    unit: "L",
    ratings: 4.6,
    numReviews: 167,
    description: "Specially treated lactose-free milk for those with lactose intolerance. Same nutrition, no discomfort.",
    image: "",
    isActive: true
  },
  {
    name: "Flavored Strawberry Milk",
    slug: "flavored-strawberry-milk",
    category: "milk",
    brand: "MilkMitra Flavors",
    price: 65,
    stock: 130,
    unit: "L",
    ratings: 4.5,
    numReviews: 223,
    description: "Delicious strawberry flavored milk made with real fruit pulp. Kids' favorite!",
    image: "",
    isActive: true
  },
  {
    name: "Chocolate Milk",
    slug: "chocolate-milk",
    category: "milk",
    brand: "MilkMitra Flavors",
    price: 65,
    stock: 140,
    unit: "L",
    ratings: 4.7,
    numReviews: 289,
    description: "Rich chocolate milk made with premium cocoa. Perfect energy booster after workout.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Vanilla Milk",
    slug: "vanilla-milk",
    category: "milk",
    brand: "MilkMitra Flavors",
    price: 60,
    stock: 110,
    unit: "L",
    ratings: 4.4,
    numReviews: 134,
    description: "Smooth vanilla flavored milk with natural vanilla extract. Great for smoothies.",
    image: "",
    isActive: true
  },
  {
    name: "Mango Milk",
    slug: "mango-milk",
    category: "milk",
    brand: "MilkMitra Flavors",
    price: 70,
    stock: 100,
    unit: "L",
    ratings: 4.6,
    numReviews: 198,
    description: "Tropical mango milk made with Alphonso mango pulp. Refreshing and nutritious.",
    image: "",
    isActive: true
  },
  {
    name: "Badam Milk",
    slug: "badam-milk",
    category: "milk",
    brand: "MilkMitra Traditional",
    price: 75,
    stock: 95,
    unit: "L",
    ratings: 4.8,
    numReviews: 267,
    description: "Traditional Indian almond milk with saffron and cardamom. Rich and nutritious.",
    image: "",
    isActive: true
  },
  {
    name: "Kesar Milk",
    slug: "kesar-milk",
    category: "milk",
    brand: "MilkMitra Royal",
    price: 90,
    stock: 70,
    unit: "L",
    ratings: 4.7,
    numReviews: 156,
    description: "Premium saffron milk with pure Kashmiri saffron. Royal taste and health benefits.",
    image: "",
    isActive: true
  },
  {
    name: "Rose Milk",
    slug: "rose-milk",
    category: "milk",
    brand: "MilkMitra Traditional",
    price: 65,
    stock: 120,
    unit: "L",
    ratings: 4.5,
    numReviews: 178,
    description: "Fragrant rose milk with natural rose essence. Refreshing summer drink.",
    image: "",
    isActive: true
  },
  {
    name: "Thandai Milk",
    slug: "thandai-milk",
    category: "milk",
    brand: "MilkMitra Traditional",
    price: 85,
    stock: 85,
    unit: "L",
    ratings: 4.6,
    numReviews: 145,
    description: "Traditional Indian thandai with nuts and spices. Perfect for festivals.",
    image: "",
    isActive: true
  },
  {
    name: "Cold Coffee Milk",
    slug: "cold-coffee-milk",
    category: "milk",
    brand: "MilkMitra Cafe",
    price: 70,
    stock: 130,
    unit: "L",
    ratings: 4.5,
    numReviews: 234,
    description: "Refreshing cold coffee milk with real coffee extract. Perfect summer cooler.",
    image: "",
    isActive: true
  },
  {
    name: "Protein Enriched Milk",
    slug: "protein-enriched-milk",
    category: "milk",
    brand: "MilkMitra Fitness",
    price: 90,
    stock: 90,
    unit: "L",
    ratings: 4.6,
    numReviews: 189,
    description: "High-protein milk with added whey protein. Perfect for bodybuilders and athletes.",
    image: "",
    isActive: true
  },
  {
    name: "Calcium Plus Milk",
    slug: "calcium-plus-milk",
    category: "milk",
    brand: "MilkMitra Health",
    price: 75,
    stock: 110,
    unit: "L",
    ratings: 4.5,
    numReviews: 167,
    description: "Calcium-fortified milk for stronger bones. Extra vitamin D for better absorption.",
    image: "",
    isActive: true
  },
  {
    name: "Farm Fresh Goat Milk",
    slug: "farm-fresh-goat-milk",
    category: "milk",
    brand: "MilkMitra Farm",
    price: 95,
    stock: 60,
    unit: "L",
    ratings: 4.4,
    numReviews: 89,
    description: "Pure goat milk from our farm goats. Easier to digest and rich in nutrients.",
    image: "",
    isActive: true
  },

  // Ghee Products (21-30)
  {
    name: "Pure Desi Ghee",
    slug: "pure-desi-ghee",
    category: "ghee",
    brand: "MilkMitra Traditional",
    price: 450,
    stock: 80,
    unit: "kg",
    ratings: 4.9,
    numReviews: 456,
    description: "Pure desi ghee made from cow milk bilona method. Aroma and taste of authentic Indian ghee.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Buffalo Ghee",
    slug: "buffalo-ghee",
    category: "ghee",
    brand: "MilkMitra Premium",
    price: 500,
    stock: 70,
    unit: "kg",
    ratings: 4.8,
    numReviews: 345,
    description: "Rich buffalo ghee with higher fat content. Perfect for cooking and traditional dishes.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "A2 Cow Ghee",
    slug: "a2-cow-ghee",
    category: "ghee",
    brand: "MilkMitra A2 Pure",
    price: 600,
    stock: 50,
    unit: "kg",
    ratings: 4.9,
    numReviews: 567,
    description: "Premium A2 ghee from Gir cows. Rich in nutrients and easier to digest.",
    image: "",
    isActive: true
  },
  {
    name: "Organic Ghee",
    slug: "organic-ghee",
    category: "ghee",
    brand: "MilkMitra Organic",
    price: 550,
    stock: 60,
    unit: "kg",
    ratings: 4.8,
    numReviews: 289,
    description: "100% organic ghee from grass-fed cows. No chemicals or preservatives.",
    image: "",
    isActive: true
  },
  {
    name: "Homemade Style Ghee",
    slug: "homemade-style-ghee",
    category: "ghee",
    brand: "MilkMitra Home",
    price: 480,
    stock: 75,
    unit: "kg",
    ratings: 4.7,
    numReviews: 234,
    description: "Homemade style ghee with authentic taste. Made using traditional methods.",
    image: "",
    isActive: true
  },
  {
    name: "Gir Cow Ghee",
    slug: "gir-cow-ghee",
    category: "ghee",
    brand: "MilkMitra Premium",
    price: 650,
    stock: 45,
    unit: "kg",
    ratings: 4.9,
    numReviews: 678,
    description: "Premium Gir cow ghee with golden color and rich aroma. Considered the best quality ghee.",
    image: "",
    isActive: true
  },
  {
    name: "Cooking Ghee",
    slug: "cooking-ghee",
    category: "ghee",
    brand: "MilkMitra Kitchen",
    price: 400,
    stock: 100,
    unit: "kg",
    ratings: 4.5,
    numReviews: 189,
    description: "Economical cooking ghee perfect for daily cooking. High smoke point.",
    image: "",
    isActive: true
  },
  {
    name: "Medicated Ghee",
    slug: "medicated-ghee",
    category: "ghee",
    brand: "MilkMitra Ayurveda",
    price: 700,
    stock: 40,
    unit: "kg",
    ratings: 4.7,
    numReviews: 156,
    description: "Ayurvedic medicated ghee with herbs. Good for health and wellness.",
    image: "",
    isActive: true
  },
  {
    name: "Flavored Ghee - Garlic",
    slug: "flavored-ghee-garlic",
    category: "ghee",
    brand: "MilkMitra Kitchen",
    price: 520,
    stock: 55,
    unit: "kg",
    ratings: 4.4,
    numReviews: 98,
    description: "Garlic flavored ghee for cooking. Adds rich flavor to dishes.",
    image: "",
    isActive: true
  },
  {
    name: "Flavored Ghee - Turmeric",
    slug: "flavored-ghee-turmeric",
    category: "ghee",
    brand: "MilkMitra Kitchen",
    price: 530,
    stock: 50,
    unit: "kg",
    ratings: 4.5,
    numReviews: 112,
    description: "Turmeric infused ghee with anti-inflammatory properties. Golden color and earthy taste.",
    image: "",
    isActive: true
  },

  // Butter Products (31-40)
  {
    name: "Salted Butter",
    slug: "salted-butter",
    category: "butter",
    brand: "MilkMitra Fresh",
    price: 120,
    stock: 150,
    unit: "kg",
    ratings: 4.6,
    numReviews: 345,
    description: "Premium salted butter perfect for spreading and cooking. Rich creamy taste.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Unsalted Butter",
    slug: "unsalted-butter",
    category: "butter",
    brand: "MilkMitra Fresh",
    price: 115,
    stock: 140,
    unit: "kg",
    ratings: 4.5,
    numReviews: 289,
    description: "Pure unsalted butter for baking and cooking. Perfect for control over salt content.",
    image: "",
    isActive: true
  },
  {
    name: "Amul Style Butter",
    slug: "amul-style-butter",
    category: "butter",
    brand: "MilkMitra Classic",
    price: 110,
    stock: 180,
    unit: "kg",
    ratings: 4.7,
    numReviews: 567,
    description: "Classic yellow butter similar to Amul. Perfect for toast and parathas.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "White Butter",
    slug: "white-butter",
    category: "butter",
    brand: "MilkMitra Traditional",
    price: 130,
    stock: 100,
    unit: "kg",
    ratings: 4.6,
    numReviews: 234,
    description: "Traditional white makhan from fresh cream. Rich and authentic taste.",
    image: "",
    isActive: true
  },
  {
    name: "Garlic Butter",
    slug: "garlic-butter",
    category: "butter",
    brand: "MilkMitra Kitchen",
    price: 140,
    stock: 80,
    unit: "kg",
    ratings: 4.5,
    numReviews: 178,
    description: "Garlic infused butter perfect for bread and cooking. Aromatic and flavorful.",
    image: "",
    isActive: true
  },
  {
    name: "Herb Butter",
    slug: "herb-butter",
    category: "butter",
    brand: "MilkMitra Kitchen",
    price: 145,
    stock: 75,
    unit: "kg",
    ratings: 4.4,
    numReviews: 145,
    description: "Mixed herb butter with parsley, thyme, and rosemary. Perfect for steaks.",
    image: "",
    isActive: true
  },
  {
    name: "Honey Butter",
    slug: "honey-butter",
    category: "butter",
    brand: "MilkMitra Sweet",
    price: 150,
    stock: 70,
    unit: "kg",
    ratings: 4.6,
    numReviews: 198,
    description: "Sweet honey butter perfect for pancakes and toast. Natural sweetness.",
    image: "",
    isActive: true
  },
  {
    name: "Peanut Butter",
    slug: "peanut-butter",
    category: "butter",
    brand: "MilkMitra Nut",
    price: 180,
    stock: 120,
    unit: "kg",
    ratings: 4.7,
    numReviews: 456,
    description: "Creamy peanut butter made from roasted peanuts. No added sugar or salt.",
    image: "",
    isActive: true
  },
  {
    name: "Almond Butter",
    slug: "almond-butter",
    category: "butter",
    brand: "MilkMitra Nut",
    price: 350,
    stock: 60,
    unit: "kg",
    ratings: 4.6,
    numReviews: 234,
    description: "Premium almond butter with roasted almonds. Rich and nutritious.",
    image: "",
    isActive: true
  },
  {
    name: "Coconut Butter",
    slug: "coconut-butter",
    category: "butter",
    brand: "MilkMitra Vegan",
    price: 280,
    stock: 80,
    unit: "kg",
    ratings: 4.5,
    numReviews: 167,
    description: "Pure coconut butter for vegan cooking. Rich coconut flavor.",
    image: "",
    isActive: true
  },

  // Cheese Products (41-55)
  {
    name: "Cheddar Cheese Block",
    slug: "cheddar-cheese-block",
    category: "cheese",
    brand: "MilkMitra Cheese",
    price: 280,
    stock: 90,
    unit: "kg",
    ratings: 4.6,
    numReviews: 345,
    description: "Premium cheddar cheese block. Perfect for sandwiches and cooking.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Mozzarella Cheese",
    slug: "mozzarella-cheese",
    category: "cheese",
    brand: "MilkMitra Cheese",
    price: 320,
    stock: 80,
    unit: "kg",
    ratings: 4.7,
    numReviews: 456,
    description: "Fresh mozzarella cheese perfect for pizza and salads. Stretchy and delicious.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Parmesan Cheese",
    slug: "parmesan-cheese",
    category: "cheese",
    brand: "MilkMitra Premium",
    price: 450,
    stock: 60,
    unit: "kg",
    ratings: 4.8,
    numReviews: 289,
    description: "Aged parmesan cheese with intense flavor. Perfect for pasta and risotto.",
    image: "",
    isActive: true
  },
  {
    name: "Cottage Cheese",
    slug: "cottage-cheese",
    category: "cheese",
    brand: "MilkMitra Fresh",
    price: 150,
    stock: 120,
    unit: "kg",
    ratings: 4.5,
    numReviews: 234,
    description: "Fresh cottage cheese high in protein. Perfect for salads and healthy meals.",
    image: "",
    isActive: true
  },
  {
    name: "Cream Cheese",
    slug: "cream-cheese",
    category: "cheese",
    brand: "MilkMitra Soft",
    price: 200,
    stock: 100,
    unit: "kg",
    ratings: 4.6,
    numReviews: 312,
    description: "Smooth cream cheese perfect for spreads and cheesecake. Rich and creamy.",
    image: "",
    isActive: true
  },
  {
    name: "Blue Cheese",
    slug: "blue-cheese",
    category: "cheese",
    brand: "MilkMitra Gourmet",
    price: 550,
    stock: 40,
    unit: "kg",
    ratings: 4.4,
    numReviews: 89,
    description: "Aged blue cheese with distinctive flavor. Perfect for gourmet dishes.",
    image: "",
    isActive: true
  },
  {
    name: "Feta Cheese",
    slug: "feta-cheese",
    category: "cheese",
    brand: "MilkMitra Mediterranean",
    price: 300,
    stock: 70,
    unit: "kg",
    ratings: 4.5,
    numReviews: 167,
    description: "Greek feta cheese in brine. Perfect for salads and Mediterranean dishes.",
    image: "",
    isActive: true
  },
  {
    name: "Gouda Cheese",
    slug: "gouda-cheese",
    category: "cheese",
    brand: "MilkMitra International",
    price: 350,
    stock: 65,
    unit: "kg",
    ratings: 4.6,
    numReviews: 145,
    description: "Dutch gouda cheese with caramel notes. Perfect for snacking.",
    image: "",
    isActive: true
  },
  {
    name: "Swiss Cheese",
    slug: "swiss-cheese",
    category: "cheese",
    brand: "MilkMitra International",
    price: 380,
    stock: 55,
    unit: "kg",
    ratings: 4.5,
    numReviews: 123,
    description: "Classic Swiss cheese with holes. Mild and nutty flavor.",
    image: "",
    isActive: true
  },
  {
    name: "Ricotta Cheese",
    slug: "ricotta-cheese",
    category: "cheese",
    brand: "MilkMitra Italian",
    price: 250,
    stock: 85,
    unit: "kg",
    ratings: 4.6,
    numReviews: 189,
    description: "Fresh ricotta cheese perfect for lasagna and desserts. Light and fluffy.",
    image: "",
    isActive: true
  },
  {
    name: "Goat Cheese",
    slug: "goat-cheese",
    category: "cheese",
    brand: "MilkMitra Farm",
    price: 320,
    stock: 60,
    unit: "kg",
    ratings: 4.4,
    numReviews: 98,
    description: "Creamy goat cheese with tangy flavor. Perfect for salads and crackers.",
    image: "",
    isActive: true
  },
  {
    name: "Provolone Cheese",
    slug: "provolone-cheese",
    category: "cheese",
    brand: "MilkMitra Italian",
    price: 340,
    stock: 70,
    unit: "kg",
    ratings: 4.5,
    numReviews: 134,
    description: "Italian provolone cheese with smoky flavor. Great for sandwiches.",
    image: "",
    isActive: true
  },
  {
    name: "Gruyère Cheese",
    slug: "gruyere-cheese",
    category: "cheese",
    brand: "MilkMitra Gourmet",
    price: 480,
    stock: 45,
    unit: "kg",
    ratings: 4.7,
    numReviews: 89,
    description: "Swiss gruyère cheese with nutty flavor. Perfect for fondue.",
    image: "",
    isActive: true
  },
  {
    name: "Processed Cheese Slices",
    slug: "processed-cheese-slices",
    category: "cheese",
    brand: "MilkMitra Kids",
    price: 180,
    stock: 150,
    unit: "kg",
    ratings: 4.4,
    numReviews: 456,
    description: "Convenient cheese slices perfect for sandwiches. Kids love them!",
    image: "",
    isActive: true
  },
  {
    name: "Cheese Spread",
    slug: "cheese-spread",
    category: "cheese",
    brand: "MilkMitra Easy",
    price: 160,
    stock: 130,
    unit: "kg",
    ratings: 4.5,
    numReviews: 312,
    description: "Creamy cheese spread perfect for crackers and bread. Easy to use.",
    image: "",
    isActive: true
  },

  // Curd/Yogurt Products (56-70)
  {
    name: "Fresh Curd",
    slug: "fresh-curd",
    category: "curd",
    brand: "MilkMitra Fresh",
    price: 50,
    stock: 200,
    unit: "kg",
    ratings: 4.7,
    numReviews: 567,
    description: "Fresh homemade style curd. Perfect for daily use.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Greek Yogurt",
    slug: "greek-yogurt",
    category: "yogurt",
    brand: "MilkMitra Premium",
    price: 120,
    stock: 100,
    unit: "kg",
    ratings: 4.8,
    numReviews: 456,
    description: "Thick and creamy Greek yogurt. High protein content.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Probiotic Curd",
    slug: "probiotic-curd",
    category: "curd",
    brand: "MilkMitra Health",
    price: 70,
    stock: 150,
    unit: "kg",
    ratings: 4.6,
    numReviews: 389,
    description: "Probiotic curd with good bacteria for gut health.",
    image: "",
    isActive: true
  },
  {
    name: "Fruit Yogurt - Strawberry",
    slug: "fruit-yogurt-strawberry",
    category: "yogurt",
    brand: "MilkMitra Flavors",
    price: 85,
    stock: 120,
    unit: "kg",
    ratings: 4.5,
    numReviews: 345,
    description: "Strawberry flavored yogurt with real fruit pieces. Kids favorite.",
    image: "",
    isActive: true
  },
  {
    name: "Fruit Yogurt - Mango",
    slug: "fruit-yogurt-mango",
    category: "yogurt",
    brand: "MilkMitra Flavors",
    price: 85,
    stock: 110,
    unit: "kg",
    ratings: 4.6,
    numReviews: 367,
    description: "Mango flavored yogurt with Alphonso mango pulp. Tropical taste.",
    image: "",
    isActive: true
  },
  {
    name: "Fruit Yogurt - Blueberry",
    slug: "fruit-yogurt-blueberry",
    category: "yogurt",
    brand: "MilkMitra Flavors",
    price: 90,
    stock: 100,
    unit: "kg",
    ratings: 4.5,
    numReviews: 289,
    description: "Blueberry yogurt with real blueberries. Antioxidant rich.",
    image: "",
    isActive: true
  },
  {
    name: "Lassi - Sweet",
    slug: "lassi-sweet",
    category: "lassi",
    brand: "MilkMitra Traditional",
    price: 40,
    stock: 180,
    unit: "L",
    ratings: 4.7,
    numReviews: 456,
    description: "Traditional sweet lassi with cardamom. Refreshing summer drink.",
    image: "",
    isActive: true
  },
  {
    name: "Lassi - Salted",
    slug: "lassi-salted",
    category: "lassi",
    brand: "MilkMitra Traditional",
    price: 35,
    stock: 200,
    unit: "L",
    ratings: 4.6,
    numReviews: 389,
    description: "Refreshing salted lassi with cumin. Perfect for digestion.",
    image: "",
    isActive: true
  },
  {
    name: "Mango Lassi",
    slug: "mango-lassi",
    category: "lassi",
    brand: "MilkMitra Traditional",
    price: 50,
    stock: 150,
    unit: "L",
    ratings: 4.8,
    numReviews: 567,
    description: "Creamy mango lassi with Alphonso mango pulp. Royal summer drink.",
    image: "",
    isActive: true
  },
  {
    name: "Rose Lassi",
    slug: "rose-lassi",
    category: "lassi",
    brand: "MilkMitra Traditional",
    price: 45,
    stock: 120,
    unit: "L",
    ratings: 4.7,
    numReviews: 234,
    description: "Fragrant rose lassi with rose water and pistachios. Royal drink.",
    image: "",
    isActive: true
  },
  {
    name: "Strawberry Lassi",
    slug: "strawberry-lassi",
    category: "lassi",
    brand: "MilkMitra Fresh",
    price: 48,
    stock: 110,
    unit: "L",
    ratings: 4.6,
    numReviews: 189,
    description: "Fresh strawberry lassi with real strawberries. Berry delight.",
    image: "",
    isActive: true
  },
  {
    name: "Buttermilk",
    slug: "buttermilk",
    category: "curd",
    brand: "MilkMitra Fresh",
    price: 25,
    stock: 250,
    unit: "L",
    ratings: 4.5,
    numReviews: 345,
    description: "Fresh buttermilk perfect for hot summers. Refreshing and cooling.",
    image: "",
    isActive: true
  },
  {
    name: "Spiced Buttermilk",
    slug: "spiced-buttermilk",
    category: "curd",
    brand: "MilkMitra Traditional",
    price: 30,
    stock: 220,
    unit: "L",
    ratings: 4.6,
    numReviews: 412,
    description: "Masala chaas with spices and curry leaves. Authentic Indian taste.",
    image: "",
    isActive: true
  },
  {
    name: "Low Fat Yogurt",
    slug: "low-fat-yogurt",
    category: "yogurt",
    brand: "MilkMitra Diet",
    price: 80,
    stock: 140,
    unit: "kg",
    ratings: 4.4,
    numReviews: 234,
    description: "Low fat yogurt for health conscious. Same taste, less calories.",
    image: "",
    isActive: true
  },
  {
    name: "Yogurt Drink - Peach",
    slug: "yogurt-drink-peach",
    category: "yogurt",
    brand: "MilkMitra Refresh",
    price: 45,
    stock: 160,
    unit: "L",
    ratings: 4.5,
    numReviews: 289,
    description: "Peach flavored yogurt drink. Refreshing and nutritious.",
    image: "",
    isActive: true
  },
  {
    name: "Yogurt Drink - Mixed Berry",
    slug: "yogurt-drink-mixed-berry",
    category: "yogurt",
    brand: "MilkMitra Refresh",
    price: 45,
    stock: 150,
    unit: "L",
    ratings: 4.4,
    numReviews: 256,
    description: "Mixed berry yogurt drink with antioxidant rich berries.",
    image: "",
    isActive: true
  },
  {
    name: "Set Curd",
    slug: "set-curd",
    category: "curd",
    brand: "MilkMitra Home",
    price: 45,
    stock: 190,
    unit: "kg",
    ratings: 4.6,
    numReviews: 378,
    description: "Traditional set curd in clay pot. Authentic homemade taste.",
    image: "",
    isActive: true
  },

  // Paneer Products (71-85)
  {
    name: "Soft Paneer",
    slug: "soft-paneer",
    category: "paneer",
    brand: "MilkMitra Fresh",
    price: 180,
    stock: 120,
    unit: "kg",
    ratings: 4.7,
    numReviews: 567,
    description: "Soft and fresh paneer perfect for curries and gravies. Melts in mouth.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Firm Paneer",
    slug: "firm-paneer",
    category: "paneer",
    brand: "MilkMitra Kitchen",
    price: 170,
    stock: 130,
    unit: "kg",
    ratings: 4.6,
    numReviews: 456,
    description: "Firm paneer perfect for grilling and tikkas. Holds shape well.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Low Fat Paneer",
    slug: "low-fat-paneer",
    category: "paneer",
    brand: "MilkMitra Diet",
    price: 190,
    stock: 100,
    unit: "kg",
    ratings: 4.5,
    numReviews: 345,
    description: "Low fat paneer for health conscious. High protein, less fat.",
    image: "",
    isActive: true
  },
  {
    name: "Malai Paneer",
    slug: "malai-paneer",
    category: "paneer",
    brand: "MilkMitra Premium",
    price: 220,
    stock: 80,
    unit: "kg",
    ratings: 4.8,
    numReviews: 678,
    description: "Creamy malai paneer with rich texture. Premium quality.",
    image: "",
    isActive: true
  },
  {
    name: "Smoked Paneer",
    slug: "smoked-paneer",
    category: "paneer",
    brand: "MilkMitra Gourmet",
    price: 250,
    stock: 60,
    unit: "kg",
    ratings: 4.6,
    numReviews: 234,
    description: "Smoked paneer with distinct flavor. Perfect for salads and wraps.",
    image: "",
    isActive: true
  },
  {
    name: "Herb Paneer",
    slug: "herb-paneer",
    category: "paneer",
    brand: "MilkMitra Kitchen",
    price: 200,
    stock: 70,
    unit: "kg",
    ratings: 4.5,
    numReviews: 189,
    description: "Paneer infused with herbs and spices. Aromatic and flavorful.",
    image: "",
    isActive: true
  },
  {
    name: "Tofu",
    slug: "tofu",
    category: "paneer",
    brand: "MilkMitra Vegan",
    price: 150,
    stock: 100,
    unit: "kg",
    ratings: 4.4,
    numReviews: 267,
    description: "Soy-based tofu for vegan options. High protein, plant-based.",
    image: "",
    isActive: true
  },
  {
    name: "Paneer Cubes",
    slug: "paneer-cubes",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 190,
    stock: 90,
    unit: "kg",
    ratings: 4.6,
    numReviews: 389,
    description: "Ready-to-use paneer cubes. Convenient for quick cooking.",
    image: "",
    isActive: true
  },
  {
    name: "Marinated Paneer",
    slug: "marinated-paneer",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 220,
    stock: 70,
    unit: "kg",
    ratings: 4.5,
    numReviews: 234,
    description: "Pre-marinated paneer for grilling. Save prep time.",
    image: "",
    isActive: true
  },
  {
    name: "Buffalo Milk Paneer",
    slug: "buffalo-milk-paneer",
    category: "paneer",
    brand: "MilkMitra Premium",
    price: 200,
    stock: 85,
    unit: "kg",
    ratings: 4.7,
    numReviews: 345,
    description: "Paneer made from buffalo milk. Richer and creamier.",
    image: "",
    isActive: true
  },
  {
    name: "Goat Milk Paneer",
    slug: "goat-milk-paneer",
    category: "paneer",
    brand: "MilkMitra Farm",
    price: 230,
    stock: 50,
    unit: "kg",
    ratings: 4.5,
    numReviews: 123,
    description: "Paneer made from goat milk. Unique flavor and easier to digest.",
    image: "",
    isActive: true
  },
  {
    name: "Organic Paneer",
    slug: "organic-paneer",
    category: "paneer",
    brand: "MilkMitra Organic",
    price: 240,
    stock: 65,
    unit: "kg",
    ratings: 4.6,
    numReviews: 189,
    description: "100% organic paneer from organic milk. No chemicals or preservatives.",
    image: "",
    isActive: true
  },
  {
    name: "Paneer Tikka",
    slug: "paneer-tikka",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 280,
    stock: 60,
    unit: "kg",
    ratings: 4.7,
    numReviews: 456,
    description: "Ready-to-cook paneer tikka with spices. Perfect for grilling.",
    image: "",
    isActive: true
  },
  {
    name: "Paneer Butter Masala",
    slug: "paneer-butter-masala",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 250,
    stock: 70,
    unit: "kg",
    ratings: 4.6,
    numReviews: 378,
    description: "Ready-to-eat paneer butter masala. Authentic taste.",
    image: "",
    isActive: true
  },
  {
    name: "Palak Paneer",
    slug: "palak-paneer",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 240,
    stock: 75,
    unit: "kg",
    ratings: 4.5,
    numReviews: 312,
    description: "Ready-to-eat palak paneer. Healthy and delicious.",
    image: "",
    isActive: true
  },
  {
    name: "Shahi Paneer",
    slug: "shahi-paneer",
    category: "paneer",
    brand: "MilkMitra Ready",
    price: 260,
    stock: 65,
    unit: "kg",
    ratings: 4.6,
    numReviews: 289,
    description: "Royal shahi paneer with cream and cashews. Rich and creamy.",
    image: "",
    isActive: true
  },

  // Cream Products (86-95)
  {
    name: "Fresh Cream",
    slug: "fresh-cream",
    category: "cream",
    brand: "MilkMitra Fresh",
    price: 120,
    stock: 100,
    unit: "L",
    ratings: 4.6,
    numReviews: 345,
    description: "Fresh heavy cream perfect for desserts and cooking. Rich and thick.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Whipping Cream",
    slug: "whipping-cream",
    category: "cream",
    brand: "MilkMitra Baking",
    price: 150,
    stock: 90,
    unit: "L",
    ratings: 4.7,
    numReviews: 456,
    description: "Premium whipping cream for cakes and desserts. Easy to whip.",
    image: "",
    isFeatured: true,
    isActive: true
  },
  {
    name: "Sour Cream",
    slug: "sour-cream",
    category: "cream",
    brand: "MilkMitra Kitchen",
    price: 100,
    stock: 110,
    unit: "kg",
    ratings: 4.5,
    numReviews: 234,
    description: "Tangy sour cream perfect for dips and toppings.",
    image: "",
    isActive: true
  },
  {
    name: "Double Cream",
    slug: "double-cream",
    category: "cream",
    brand: "MilkMitra Premium",
    price: 140,
    stock: 80,
    unit: "L",
    ratings: 4.6,
    numReviews: 289,
    description: "Extra rich double cream with 48% fat. Premium quality.",
    image: "",
    isActive: true
  },
  {
    name: "Single Cream",
    slug: "single-cream",
    category: "cream",
    brand: "MilkMitra Lite",
    price: 90,
    stock: 120,
    unit: "L",
    ratings: 4.4,
    numReviews: 189,
    description: "Light single cream with 18% fat. Perfect for coffee and soups.",
    image: "",
    isActive: true
  },
  {
    name: "Coconut Cream",
    slug: "coconut-cream",
    category: "cream",
    brand: "MilkMitra Vegan",
    price: 130,
    stock: 70,
    unit: "L",
    ratings: 4.5,
    numReviews: 167,
    description: "Rich coconut cream for vegan cooking. Tropical flavor.",
    image: "",
    isActive: true
  },
  {
    name: "Creme Fraiche",
    slug: "creme-fraiche",
    category: "cream",
    brand: "MilkMitra Gourmet",
    price: 180,
    stock: 60,
    unit: "kg",
    ratings: 4.6,
    numReviews: 134,
    description: "French style cultured cream. Rich and tangy.",
    image: "",
    isActive: true
  },
  {
    name: "Clotted Cream",
    slug: "clotted-cream",
    category: "cream",
    brand: "MilkMitra Traditional",
    price: 200,
    stock: 50,
    unit: "kg",
    ratings: 4.7,
    numReviews: 98,
    description: "Traditional clotted cream for scones. Rich and creamy.",
    image: "",
    isActive: true
  },
  {
    name: "Mascarpone Cheese",
    slug: "mascarpone-cheese",
    category: "cheese",
    brand: "MilkMitra Italian",
    price: 220,
    stock: 65,
    unit: "kg",
    ratings: 4.6,
    numReviews: 178,
    description: "Italian mascarpone perfect for tiramisu. Creamy and smooth.",
    image: "",
    isActive: true
  },
  {
    name: "Cream Cheese Spread",
    slug: "cream-cheese-spread",
    category: "cream",
    brand: "MilkMitra Easy",
    price: 140,
    stock: 100,
    unit: "kg",
    ratings: 4.5,
    numReviews: 256,
    description: "Creamy cheese spread perfect for bagels and toast.",
    image: "",
    isActive: true
  },

  // Sweets & Desserts (96-100)
  {
    name: "Rasgulla",
    slug: "rasgulla",
    category: "sweets",
    brand: "MilkMitra Sweets",
    price: 180,
    stock: 80,
    unit: "kg",
    ratings: 4.7,
    numReviews: 567,
    description: "Soft spongy rasgulla in sugar syrup. Bengali sweet delight.",
    image: "https://images.unsplash.com/photo-1666190090727-0d849631812a?w=800&q=80",
    isActive: true
  },
  {
    name: "Gulab Jamun",
    slug: "gulab-jamun",
    category: "sweets",
    brand: "MilkMitra Sweets",
    price: 200,
    stock: 75,
    unit: "kg",
    ratings: 4.8,
    numReviews: 678,
    description: "Soft gulab jamun in rose flavored syrup. Classic Indian sweet.",
    image: "https://images.unsplash.com/photo-1666190090727-0d849631812a?w=800&q=80",
    isActive: true
  },
  {
    name: "Kaju Katli",
    slug: "kaju-katli",
    category: "sweets",
    brand: "MilkMitra Sweets",
    price: 450,
    stock: 60,
    unit: "kg",
    ratings: 4.7,
    numReviews: 456,
    description: "Premium kaju katli with silver foil. Cashew delight.",
    image: "https://images.unsplash.com/photo-1666190090727-0d849631812a?w=800&q=80",
    isActive: true
  },
  {
    name: "Milk Cake",
    slug: "milk-cake",
    category: "cake",
    brand: "MilkMitra Sweets",
    price: 320,
    stock: 70,
    unit: "kg",
    ratings: 4.6,
    numReviews: 345,
    description: "Traditional milk cake (Kalakand). Rich and grainy texture.",
    image: "",
    isActive: true
  },
  {
    name: "Rasmalai",
    slug: "rasmalai",
    category: "sweets",
    brand: "MilkMitra Sweets",
    price: 250,
    stock: 65,
    unit: "kg",
    ratings: 4.8,
    numReviews: 589,
    description: "Soft rasmalai in thickened milk with saffron. Royal dessert.",
    image: "https://images.unsplash.com/photo-1666190090727-0d849631812a?w=800&q=80",
    isActive: true
  }
];

async function seedProducts() {
  try {
    console.log('Connecting to MongoDB...');
    await mongoose.connect(mongoURI);
    console.log('Connected to MongoDB');

    // Clear existing products
    console.log('Clearing existing products...');
    await Product.deleteMany({});
    console.log('Existing products cleared');

    // Insert new products
    console.log('Inserting 100 products...');
    const brandedProducts = products.map((product) => ({
      ...product,
      brand: String(product.brand || '').replace(/^MilkMitra\b/, 'Pinqoza')
    }));

    await Product.insertMany(brandedProducts);
    console.log('100 products inserted successfully');

    console.log('Seeding completed!');

  } catch (error) {
    console.error('Error seeding products:', error.message);
  } finally {
    await mongoose.connection.close();
    console.log('Database connection closed');
  }
}

seedProducts();
